export type ArtworkCategory = 'Painting' | 'Works on Paper' | 'Object'

export type Artwork = {
  id: string
  number: string
  title: string
  subtitle: string
  category: ArtworkCategory
  year: number
  medium: string
  dimensions: string
  price: number
  status: 'Available' | 'Sold' | 'Edition'
  featured?: boolean
  image: string
  credit: string
  creditUrl: string
  description: string
  accent: string
}

export const artworks: Artwork[] = [
  {
    id: 'afterglow',
    number: '01',
    title: 'Afterglow',
    subtitle: 'a quiet edge of summer',
    category: 'Painting',
    year: 2026,
    medium: 'Oil and pigment on linen',
    dimensions: '36 × 48 in',
    price: 1800,
    status: 'Available',
    featured: true,
    image: 'https://images.unsplash.com/photo-1536851101967-55988a52f455?auto=format&fit=crop&w=1800&q=88',
    credit: 'Ivan Bandura / Unsplash',
    creditUrl: 'https://unsplash.com/photos/abstract-painting-artwork-zBY6td_nVNA',
    description: 'A study of suspended color and the few seconds after light leaves a room. Built in thin, transparent layers so that darker passages remain luminous.',
    accent: '#8d6b42',
  },
  {
    id: 'blue-hour',
    number: '02',
    title: 'Blue Hour',
    subtitle: 'memory, translated',
    category: 'Painting',
    year: 2026,
    medium: 'Acrylic, graphite and wax on panel',
    dimensions: '24 × 32 in',
    price: 1250,
    status: 'Available',
    featured: true,
    image: 'https://images.unsplash.com/photo-1532799755889-1247a1b7f10e?auto=format&fit=crop&w=1600&q=88',
    credit: 'Steve A Johnson / Unsplash',
    creditUrl: 'https://unsplash.com/photos/abstract-painting-Cdr1ryVJyQA',
    description: 'Built around cool blues, chalky whites and a single violet interruption. The work sits between landscape and abstraction without committing fully to either.',
    accent: '#53657f',
  },
  {
    id: 'white-room',
    number: '03',
    title: 'White Room',
    subtitle: 'the architecture of attention',
    category: 'Works on Paper',
    year: 2025,
    medium: 'Ink and charcoal on cotton',
    dimensions: '18 × 24 in',
    price: 680,
    status: 'Edition',
    featured: true,
    image: 'https://images.unsplash.com/photo-1498721409281-998093cc905b?auto=format&fit=crop&w=1600&q=88',
    credit: 'CHUTTERSNAP / Unsplash',
    creditUrl: 'https://unsplash.com/photos/abstract-painting-uj1tRjP5UI0',
    description: 'A work about framing: what is present, what is cropped, and what the eye invents to complete the scene. Edition of 25.',
    accent: '#9a8f79',
  },
  {
    id: 'the-witness',
    number: '04',
    title: 'The Witness',
    subtitle: 'one body, many images',
    category: 'Object',
    year: 2025,
    medium: 'Steel, found wood and linen',
    dimensions: '22 × 18 × 14 in',
    price: 920,
    status: 'Sold',
    image: 'https://images.unsplash.com/photo-1770129703548-e1ced0e4f118?auto=format&fit=crop&w=1600&q=88',
    credit: 'Fons Heijnsbroek / Unsplash',
    creditUrl: 'https://unsplash.com/photos/abstract-painting-with-bold-brushstrokes-and-vibrant-colors-S1Cv0sXA7uI',
    description: 'A small sculptural study of looking. The object is intentionally architectural, more like a threshold than a figure.',
    accent: '#7a574b',
  },
  {
    id: 'green-memory',
    number: '05',
    title: 'Green Memory',
    subtitle: 'notes from a slower place',
    category: 'Painting',
    year: 2025,
    medium: 'Oil, wax and earth pigment',
    dimensions: '40 × 40 in',
    price: 1600,
    status: 'Available',
    image: 'https://images.unsplash.com/photo-1536851101967-55988a52f455?auto=format&fit=crop&w=1600&q=88',
    credit: 'Helena Lopes / Unsplash',
    creditUrl: 'https://unsplash.com/photos/abstract-painting-artwork-zBY6td_nVNA',
    description: 'Green is treated here less as a color than as a temperature. The surface shifts between forest, mineral and oxidized metal.',
    accent: '#52634d',
  },

  {
    id: 'garden-shadow',
    number: '07',
    title: 'Garden Shadow',
    subtitle: 'where the room meets the vine',
    category: 'Works on Paper',
    year: 2026,
    medium: 'Pigment, graphite and pressed foliage',
    dimensions: '22 × 30 in',
    price: 520,
    status: 'Edition',
    featured: true,
    image: 'https://images.unsplash.com/photo-1676360437958-842f51870ffa?auto=format&fit=crop&w=1600&q=88',
    credit: 'Junaid Khan / Unsplash',
    creditUrl: 'https://unsplash.com/photos/a-plant-casting-a-shadow-on-a-wall-eDkaxvFvQTk',
    description: 'A botanical shadow study built around the tension between an object and its silhouette. The image is intentionally quiet, almost architectural.',
    accent: '#7f8b70',
  },
  {
    id: 'secret-garden',
    number: '08',
    title: 'Secret Garden',
    subtitle: 'green, then green again',
    category: 'Painting',
    year: 2026,
    medium: 'Oil, earth pigment and wax',
    dimensions: '40 × 60 in',
    price: 2100,
    status: 'Available',
    image: 'https://images.unsplash.com/photo-1762698580042-c0ebe7d442d3?auto=format&fit=crop&w=1800&q=88',
    credit: 'Kseniia Zapiatkina / Unsplash',
    creditUrl: 'https://unsplash.com/photos/armchair-overgrown-with-lush-green-vines-and-purple-flowers-EfHD1u_p-Bw',
    description: 'A lush study of enclosure and abundance. The surface borrows the density of a garden and the softness of an old theatre curtain.',
    accent: '#385647',
  },
  {
    id: 'glass-flowers',
    number: '09',
    title: 'Glass Flowers',
    subtitle: 'petals suspended in light',
    category: 'Works on Paper',
    year: 2025,
    medium: 'Photographic transfer, oil pastel and graphite',
    dimensions: '16 × 22 in',
    price: 460,
    status: 'Edition',
    featured: true,
    image: 'https://images.unsplash.com/photo-1746876306717-f54b5024e6b2?auto=format&fit=crop&w=1600&q=88',
    credit: 'Danielle Suijkerbuijk / Unsplash',
    creditUrl: 'https://unsplash.com/photos/pink-flowers-arranged-symmetrically-against-a-blue-backdrop-aJ_69HNfqZY',
    description: 'Flowers appear through a veil of pale blue glass. It is less a botanical image than a study in refraction, softness and distance.',
    accent: '#c08da1',
  },
  {
    id: 'winter-leaves',
    number: '10',
    title: 'Winter Leaves',
    subtitle: 'the dark edge of green',
    category: 'Object',
    year: 2025,
    medium: 'Found wood, linen and botanical print',
    dimensions: '20 × 15 × 8 in',
    price: 980,
    status: 'Available',
    featured: true,
    image: 'https://images.unsplash.com/photo-1768528796480-107540f18ef6?auto=format&fit=crop&w=1600&q=88',
    credit: 'Aaron Burden / Unsplash',
    creditUrl: 'https://unsplash.com/photos/dark-green-leaves-with-small-red-berries-and-sunlight-Yq8lxX8Kyk8',
    description: 'A sculptural arrangement built around dark foliage, small points of red and a narrow opening for light.',
    accent: '#2d5449',
  },
  {
    id: 'bouquet-light',
    number: '11',
    title: 'Bouquet / Light',
    subtitle: 'a shadow before the bloom',
    category: 'Painting',
    year: 2026,
    medium: 'Oil and soft pastel on linen',
    dimensions: '30 × 40 in',
    price: 1450,
    status: 'Available',
    image: 'https://images.unsplash.com/photo-1761746555964-54d189e38bfd?auto=format&fit=crop&w=1600&q=88',
    credit: 'Evie S. / Unsplash',
    creditUrl: 'https://unsplash.com/photos/a-vibrant-bouquet-of-assorted-flowers-casts-a-shadow-Y7PJLN9DgXY',
    description: 'A study of flowers and projected shadow. The composition is deliberately spare so light becomes part of the subject.',
    accent: '#b26c83',
  },
  {
    id: 'studio-light',
    number: '06',
    title: 'Studio Light',
    subtitle: 'process / fragment',
    category: 'Works on Paper',
    year: 2026,
    medium: 'Graphite, oil stick and pastel',
    dimensions: '12 × 16 in',
    price: 340,
    status: 'Available',
    image: 'https://images.unsplash.com/photo-1498721409281-998093cc905b?auto=format&fit=crop&w=1400&q=82',
    credit: 'Engin Akyurt / Unsplash',
    creditUrl: 'https://unsplash.com/photos/abstract-painting-uj1tRjP5UI0',
    description: 'A smaller work made between larger canvases. The gestures are deliberately exposed rather than refined away.',
    accent: '#695b48',
  },
]

export const collections = [
  {
    title: 'Field Notes',
    count: '11 works',
    description: 'Color studies, fragments and works made in direct response to landscape.',
  },
  {
    title: 'Interior Weather',
    count: '07 works',
    description: 'A slower series about rooms, memory, atmosphere and the architecture of attention.',
  },
  {
    title: 'Small Objects',
    count: '05 works',
    description: 'Sculptural studies that sit between furniture, image and threshold.',
  },
]

export const courses = [
  {
    id: 'visual-language',
    title: 'Finding Your Visual Language',
    eyebrow: '04 sessions',
    duration: '2 weeks',
    price: 95,
    description: 'A small-group workshop about taste, references, repetition and developing a visual vocabulary you can actually use.',
  },
  {
    id: 'color-atmosphere',
    title: 'Color & Atmosphere',
    eyebrow: '06 sessions',
    duration: '3 weeks',
    price: 140,
    description: 'Learn how temperature, value and edge control can create a sense of place without over-explaining the image.',
  },
  {
    id: 'process-studio',
    title: 'Process Studio',
    eyebrow: '01:1 mentorship',
    duration: '75 minutes',
    price: 80,
    description: 'A focused portfolio and process review for emerging artists who need a clearer next step.',
  },
]

export const studioFacts = [
  ['12', 'years working across painting, image and object'],
  ['34', 'works currently archived in the studio catalogue'],
  ['18', 'private commissions completed since 2021'],
]

export const navItems = [
  ['/', 'Index'],
  ['/works', 'Works'],
  ['/shop', 'Shop'],
  ['/learn', 'Learn'],
  ['/studio', 'Studio'],
  ['/contact', 'Contact'],
] as const
