export type ArtworkCategory = 'Painting' | 'Works on Paper' | 'Object'

export type Artwork = {
  id: string
  number: string
  title: string
  subtitle: string
  category: ArtworkCategory
  year: number
  medium: string
  dimensions: string
  price: number
  status: 'Available' | 'Sold' | 'Edition'
  featured?: boolean
  image: string
  credit: string
  creditUrl: string
  description: string
  accent: string
}

export const artworks: Artwork[] = [
  {
    id: 'untitled-first-abstract',
    number: '01',
    title: 'Untitled',
    subtitle: 'First Abstract Watercolor',
    category: 'Works on Paper',
    year: 1913,
    medium: 'Graphite, ink and watercolor on paper',
    dimensions: '49.6 × 64.8 cm',
    price: 0,
    status: 'Sold',
    featured: true,
    image: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/79/Untitled_%28First_Abstract_Watercolor%29_by_Wassily_Kandinsky.jpg/960px-Untitled_%28First_Abstract_Watercolor%29_by_Wassily_Kandinsky.jpg',
    credit: 'Wassily Kandinsky / Wikimedia Commons',
    creditUrl: 'https://commons.wikimedia.org/wiki/File:Untitled_(First_Abstract_Watercolor)_by_Wassily_Kandinsky.jpg',
    description: 'An early abstract watercolor in which loose marks, transparent colour and directional lines replace a conventional subject.',
    accent: '#536a61',
  },
  {
    id: 'einfach-simple',
    number: '02',
    title: 'Einfach / Simple',
    subtitle: 'Wassily Kandinsky',
    category: 'Works on Paper',
    year: 1916,
    medium: 'Watercolor and ink on paper',
    dimensions: 'Study on paper',
    price: 0,
    status: 'Sold',
    featured: true,
    image: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/19/Wassily_Kandinsky_-_Einfach_%28Simple%29_%281916%29.jpg/1280px-Wassily_Kandinsky_-_Einfach_%28Simple%29_%281916%29.jpg',
    credit: 'Wassily Kandinsky / Wikimedia Commons',
    creditUrl: 'https://commons.wikimedia.org/wiki/File:Wassily_Kandinsky_-_Einfach_(Simple)_(1916).jpg',
    description: 'A restrained composition of lines, isolated shapes and colour accents, closer to visual notation than representation.',
    accent: '#8a7351',
  },
  {
    id: 'abstract-interpretation',
    number: '03',
    title: 'Abstract Interpretation',
    subtitle: 'Wassily Kandinsky',
    category: 'Painting',
    year: 1925,
    medium: 'Oil on canvas',
    dimensions: 'Museum record',
    price: 0,
    status: 'Sold',
    featured: true,
    image: 'https://upload.wikimedia.org/wikipedia/commons/6/65/Kandinsky_-_Abstract_Interpretation%2C_1925.jpg',
    credit: 'Wassily Kandinsky / Wikimedia Commons',
    creditUrl: 'https://commons.wikimedia.org/wiki/File:Kandinsky_-_Abstract_Interpretation,_1925.jpg',
    description: 'Geometric fragments, diagonals and saturated fields assembled as a self-contained visual system.',
    accent: '#394d47',
  },
  {
    id: 'svanen-no17',
    number: '04',
    title: 'The Swan, No. 17',
    subtitle: 'Hilma af Klint',
    category: 'Painting',
    year: 1915,
    medium: 'Tempera on canvas',
    dimensions: 'Museum record',
    price: 0,
    status: 'Sold',
    featured: true,
    image: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/00/Hilma_af_Klint%2C_1915%2C_Svanen%2C_No._17.jpg/960px-Hilma_af_Klint%2C_1915%2C_Svanen%2C_No._17.jpg',
    credit: 'Hilma af Klint / Wikimedia Commons',
    creditUrl: 'https://commons.wikimedia.org/wiki/File:Hilma_af_Klint,_1915,_Svanen,_No._17.jpg',
    description: 'A symbolic circular construction balancing black, white, red, blue and gold around a central axis.',
    accent: '#536a61',
  },
  {
    id: 'primordial-chaos',
    number: '05',
    title: 'Primordial Chaos No. 16',
    subtitle: 'Hilma af Klint',
    category: 'Painting',
    year: 1906,
    medium: 'Oil and pigment on canvas',
    dimensions: 'Museum record',
    price: 0,
    status: 'Sold',
    featured: true,
    image: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/56/Hilma_af_Klint_-_1906-1907_-_Primordial_Chaos_-_No_16_From_The_WU-ROSEN_Series_Grupp_1.jpg/500px-Hilma_af_Klint_-_1906-1907_-_Primordial_Chaos_-_No_16_From_The_WU-ROSEN_Series_Grupp_1.jpg',
    credit: 'Hilma af Klint / Wikimedia Commons',
    creditUrl: 'https://commons.wikimedia.org/wiki/File:Hilma_af_Klint_-_1906-1907_-_Primordial_Chaos_-_No_16_From_The_WU-ROSEN_Series_Grupp_1.jpg',
    description: 'A deep blue field crossed by repeated spirals and a concentrated golden centre, somewhere between diagram and painting.',
    accent: '#526a73',
  },
  {
    id: 'abstraction-mondrian',
    number: '06',
    title: 'Abstraction',
    subtitle: 'Piet Mondrian',
    category: 'Painting',
    year: 1939,
    medium: 'Oil on canvas',
    dimensions: 'Museum record',
    price: 0,
    status: 'Sold',
    featured: true,
    image: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Abstraction%2C_Mondrian%2C_Kimbell_1939.png',
    credit: 'Piet Mondrian / Wikimedia Commons',
    creditUrl: 'https://commons.wikimedia.org/wiki/File:Abstraction,_Mondrian,_Kimbell_1939.png',
    description: 'A disciplined field of vertical and horizontal lines interrupted by small colour blocks and open space.',
    accent: '#57645e',
  },
  {
    id: 'rythme-joie-de-vivre',
    number: '07',
    title: 'Rythme, Joie de vivre',
    subtitle: 'Robert Delaunay',
    category: 'Painting',
    year: 1930,
    medium: 'Oil on canvas',
    dimensions: '200 × 228 cm',
    price: 0,
    status: 'Sold',
    featured: true,
    image: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/Robert_Delaunay_-_Rythme%2C_Joie_de_vivre.jpg/960px-Robert_Delaunay_-_Rythme%2C_Joie_de_vivre.jpg',
    credit: 'Robert Delaunay / Wikimedia Commons',
    creditUrl: 'https://commons.wikimedia.org/wiki/File:Robert_Delaunay_-_Rythme,_Joie_de_vivre.jpg',
    description: 'Concentric colour rhythms turn geometry into movement, using repetition and contrast rather than narrative.',
    accent: '#5f755e',
  },
  {
    id: 'flowering-tree',
    number: '08',
    title: 'Abstraction with Reference to a Flowering Tree',
    subtitle: 'Paul Klee',
    category: 'Painting',
    year: 1925,
    medium: 'Oil on board',
    dimensions: '39.3 × 39.1 cm',
    price: 0,
    status: 'Sold',
    featured: true,
    image: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/43/Abstraction_with_Reference_to_a_Flowering_Tree%2C_by_Paul_Klee%2C_1925%2C_oil_on_carton_-_National_Museum_of_Modern_Art%2C_Tokyo_-_DSC06558.JPG/960px-Abstraction_with_Reference_to_a_Flowering_Tree%2C_by_Paul_Klee%2C_1925%2C_oil_on_carton_-_National_Museum_of_Modern_Art%2C_Tokyo_-_DSC06558.JPG',
    credit: 'Paul Klee / Wikimedia Commons',
    creditUrl: 'https://commons.wikimedia.org/wiki/File:Abstraction_with_Reference_to_a_Flowering_Tree,_by_Paul_Klee,_1925,_oil_on_carton_-_National_Museum_of_Modern_Art,_Tokyo_-_DSC06558.JPG',
    description: 'A compact mosaic of muted squares and shifting tones, balancing structure with the suggestion of organic growth.',
    accent: '#68705c',
  },
  {
    id: 'suprematist-composition',
    number: '09',
    title: 'Suprematist Composition',
    subtitle: 'Kazimir Malevich',
    category: 'Painting',
    year: 1915,
    medium: 'Oil on canvas',
    dimensions: 'Museum record',
    price: 0,
    status: 'Sold',
    featured: true,
    image: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cb/Kazimir_malevich_suprematist_composition.jpg/250px-Kazimir_malevich_suprematist_composition.jpg',
    credit: 'Kazimir Malevich / Wikimedia Commons',
    creditUrl: 'https://commons.wikimedia.org/wiki/File:Kazimir_malevich_suprematist_composition.jpg',
    description: 'Floating bars, planes and colour blocks suspended against a pale field with almost architectural precision.',
    accent: '#3f5a50',
  },
  {
    id: 'magnetic-construction',
    number: '10',
    title: 'Magnetic Construction',
    subtitle: 'Kazimir Malevich',
    category: 'Painting',
    year: 1916,
    medium: 'Oil on canvas',
    dimensions: 'Museum record',
    price: 0,
    status: 'Sold',
    featured: true,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Kazimir_Malevich%2C_Magnetic_Construction_%28S-240%29%2C_1916.jpg/960px-Kazimir_Malevich%2C_Magnetic_Construction_%28S-240%29%2C_1916.jpg',
    credit: 'Kazimir Malevich / Wikimedia Commons',
    creditUrl: 'https://commons.wikimedia.org/wiki/File:Kazimir_Malevich,_Magnetic_Construction_(S-240),_1916.jpg',
    description: 'A dynamic construction of intersecting bars and isolated vectors, with space doing as much work as colour.',
    accent: '#465f59',
  },
  {
    id: 'the-cathedral',
    number: '11',
    title: 'The Cathedral',
    subtitle: 'František Kupka',
    category: 'Painting',
    year: 1913,
    medium: 'Oil on canvas',
    dimensions: 'Museum record',
    price: 0,
    status: 'Sold',
    featured: true,
    image: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6f/Cuadro_de_Franti%C5%A1ek_Kupka.webp/960px-Cuadro_de_Franti%C5%A1ek_Kupka.webp',
    credit: 'František Kupka / Wikimedia Commons',
    creditUrl: 'https://commons.wikimedia.org/wiki/File:Cuadro_de_Franti%C5%A1ek_Kupka.webp',
    description: 'Deep blue, red and black vertical planes form an almost architectural abstraction with a strong nocturnal character.',
    accent: '#435968',
  },
  {
    id: 'thunder-shower',
    number: '12',
    title: 'Thunder Shower',
    subtitle: 'Arthur Dove',
    category: 'Painting',
    year: 1940,
    medium: 'Oil and wax emulsion on canvas',
    dimensions: 'Museum record',
    price: 0,
    status: 'Sold',
    featured: true,
    image: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fa/Thunder_Shower_by_Arthur_Dove%2C_1940%2C_oil_and_wax.JPG/960px-Thunder_Shower_by_Arthur_Dove%2C_1940%2C_oil_and_wax.JPG',
    credit: 'Arthur Dove / Wikimedia Commons',
    creditUrl: 'https://commons.wikimedia.org/wiki/File:Thunder_Shower_by_Arthur_Dove,_1940,_oil_and_wax.JPG',
    description: 'A fluid American abstraction where atmospheric force is expressed through layered shapes and compressed colour.',
    accent: '#5a6f61',
  },
]

export const collections = [
  {
    title: 'Constructed Space',
    count: '04 works',
    description: 'Geometric abstraction, measured lines and compositions built from visual systems.',
  },
  {
    title: 'Symbolic Fields',
    count: '04 works',
    description: 'Circular forms, diagrams, spirals and images that sit between painting and symbol.',
  },
  {
    title: 'Atmospheric Abstraction',
    count: '04 works',
    description: 'Colour, rhythm and natural suggestion reduced until only visual structure remains.',
  },
]

export const courses = [
  {
    id: 'visual-language',
    title: 'Reading Abstraction',
    eyebrow: '04 sessions',
    duration: '2 weeks',
    price: 95,
    description: 'A guided study of rhythm, scale, colour, geometry and visual hierarchy through abstract painting.',
  },
  {
    id: 'color-atmosphere',
    title: 'Colour & Structure',
    eyebrow: '06 sessions',
    duration: '3 weeks',
    price: 140,
    description: 'Explore how colour relationships and simple shapes can carry tension without a literal subject.',
  },
  {
    id: 'process-studio',
    title: 'Private Portfolio Review',
    eyebrow: '01:1',
    duration: '75 minutes',
    price: 80,
    description: 'A focused review of presentation, image selection and visual identity for an emerging creative portfolio.',
  },
]

export const studioFacts = [
  ['12', 'paintings currently in the digital salon'],
  ['08', 'artists represented across early modern abstraction'],
  ['01', 'visual language — no decorative noise'],
]

export const navItems = [
  ['/', 'Index'],
  ['/works', 'Collection'],
  ['/learn', 'Journal'],
  ['/studio', 'Studio'],
  ['/contact', 'Contact'],
] as const
